<!DOCTYPE html><html><head><title>R: Create an error object</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css">
<script type="text/javascript">
const macros = { "\\R": "\\textsf{R}", "\\code": "\\texttt"};
function processMathHTML() {
    var l = document.getElementsByClassName('reqn');
    for (let e of l) { katex.render(e.textContent, e, { throwOnError: false, macros }); }
    return;
}</script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js"
    onload="processMathHTML();"></script>
<link rel="stylesheet" type="text/css" href="R.css" />
</head><body><div class="container">

<table style="width: 100%;"><tr><td>new_callr_crash_error {callr}</td><td style="text-align: right;">R Documentation</td></tr></table>

<h2 id='new_callr_crash_error'>Create an error object</h2>

<h3>Description</h3>

<p>There are two kinds of errors, both have class <code>callr_error</code>:
</p>

<ol>
<li><p> the first one is thrown after a timeout: <code>callr_timeout_error</code>.
</p>
</li>
<li><p> the second one is thrown after an R error (in the other session):
<code>callr_status_error</code>.
</p>
</li></ol>



<h3>Usage</h3>

<pre><code class='language-R'>new_callr_crash_error(out, msg = NULL)
</code></pre>


<h3>Arguments</h3>

<table>
<tr><td><code id="new_callr_crash_error_:_out">out</code></td>
<td>
<p>The object returned by <code><a href="../../callr/help/run.html">run()</a></code>.</p>
</td></tr>
<tr><td><code id="new_callr_crash_error_:_msg">msg</code></td>
<td>
<p>An extra message to add to the error message.</p>
</td></tr>
</table>

<hr /><div style="text-align: center;">[Package <em>callr</em> version 3.7.3 <a href="00Index.html">Index</a>]</div>
</div>
</body></html>
